import { Household, Pet, PetEvent, SupportedLocale, EventType, AuthUser, SignUpDTO, SignInDTO, TimeRangeFilter, TreatmentScheduleItem } from '@dooty/shared';
type Listener = () => void;
export interface PendingInviteItem {
    code: string;
    role: string;
    when: string;
    expiresAt: string;
}
declare class AppStateManager {
    private listeners;
    currentUser: AuthUser | null;
    currentHousehold: Household | null;
    userHouseholds: Household[];
    currentPet: Pet | null;
    pets: Pet[];
    events: PetEvent[];
    activeTab: 'today' | 'map' | 'history' | 'analytics' | 'import' | 'settings' | 'invite' | 'dog' | 'deep' | 'wrapped';
    authView: 'signin' | 'signup' | 'dogsetup' | 'join' | 'joindetails';
    currentLocale: SupportedLocale;
    isOnline: boolean;
    pendingSyncCount: number;
    isSyncing: boolean;
    isApiActive: boolean;
    activeApiRequests: number;
    analyticsTimeRange: TimeRangeFilter;
    userAvatar: string;
    track: Record<string, boolean>;
    nudges: Record<string, boolean>;
    pendingInvites: PendingInviteItem[];
    loggerModalOpen: boolean;
    loggerEventType: EventType | null;
    editingEvent: PetEvent | null;
    photoModalOpen: boolean;
    photoModalTarget: 'pet' | 'user' | 'member';
    photoModalTargetId: string;
    photoModalCurrentAvatar: string;
    photoModalTitle: string;
    isLoading: boolean;
    petSwitcherOpen: boolean;
    treatmentsDrawerOpen: boolean;
    treatments: TreatmentScheduleItem[];
    historyMonthOffset: number;
    historySelectedDay: number | null;
    historyTypeFilters: string[];
    historyMemberFilter: string;
    historySearchOpen: boolean;
    historySearchQuery: string;
    activeWalk: {
        startTime: number;
        pausedTotal: number;
        pausedAt: number | null;
        route: [number, number][];
        petIds: string[];
        currentLat?: number;
        currentLng?: number;
        startLat?: number;
        startLng?: number;
        startLocationName?: string;
        endLat?: number;
        endLng?: number;
        endLocationName?: string;
        distanceMeters: number;
        geoWatchId?: number;
    } | null;
    walkView: 'live' | 'summary' | null;
    walkHomeAsk: boolean;
    homeAsked: boolean;
    walkTimerInterval?: any;
    walkSummaryData: {
        durationSec: number;
        distanceKm: number;
        pace: string;
        route: [number, number][];
        petNames: string[];
        startTime: string;
        endTime: string;
        startLat?: number;
        startLng?: number;
        startLocationName?: string;
        endLat?: number;
        endLng?: number;
        endLocationName?: string;
    } | null;
    constructor();
    subscribe(listener: Listener): () => void;
    private notify;
    get t(): import("@dooty/shared").TranslationSchema;
    setLocale(locale: SupportedLocale): void;
    setActiveTab(tab: 'today' | 'map' | 'history' | 'analytics' | 'import' | 'settings' | 'invite' | 'dog' | 'deep' | 'wrapped'): void;
    openPetSwitcher(): void;
    closePetSwitcher(): void;
    selectPetById(petId: string): void;
    openTreatmentsDrawer(): void;
    closeTreatmentsDrawer(): void;
    loadTreatmentsForPet(petId?: string): Promise<void>;
    saveTreatments(): void;
    formatTreatmentLeft(due: number): string;
    formatTreatmentDueDate(dueDays: number): string;
    getTreatmentEveryLabel(every: number): string;
    getTreatmentSkin(due: number): {
        bg: string;
        chip: string;
        fg: string;
        sub: string;
        anim: string;
    };
    getNextTreatment(): {
        item: null;
        name: string;
        tag: string;
        left: string;
        date: string;
        skin: {
            bg: string;
            chip: string;
            fg: string;
            sub: string;
            anim: string;
        };
    } | {
        item: TreatmentScheduleItem;
        name: string;
        tag: string;
        left: string;
        date: string;
        skin: {
            bg: string;
            chip: string;
            fg: string;
            sub: string;
            anim: string;
        };
    };
    giveTreatment(id: string): {
        title: string;
        sub: string;
    };
    addTreatment(opts: {
        name: string;
        dose: string;
        every: number;
    }): {
        title: string;
        sub: string;
    };
    removeTreatment(id: string): {
        title: string;
        sub: string;
    };
    setHistoryMonthOffset(offset: number): void;
    setHistorySelectedDay(day: number | null): void;
    toggleHistoryTypeFilter(typeId: string): void;
    setHistoryMemberFilter(member: string): void;
    clearHistoryFilters(): void;
    setHistorySearchOpen(open: boolean): void;
    setHistorySearchQuery(query: string): void;
    startLiveWalk(petIds?: string[]): void;
    private computeDistanceMeters;
    private tryReverseGeocodeForWalk;
    getWalkSeconds(): number;
    getWalkDistanceKm(): string;
    getWalkPace(): string;
    pauseLiveWalk(): void;
    minimizeWalk(): void;
    expandWalk(): void;
    keepWalking(): void;
    endLiveWalk(): void;
    saveLiveWalk(notes?: string, photoUrl?: string): Promise<void>;
    discardLiveWalk(): void;
    setAuthView(view: 'signin' | 'signup' | 'dogsetup' | 'join' | 'joindetails'): void;
    setTrackingPreference(key: string, value: boolean): void;
    setNudgePreference(key: string, value: boolean): void;
    setAnalyticsTimeRange(range: TimeRangeFilter): void;
    openLogger(eventType?: EventType | null): void;
    openLoggerForEdit(event: PetEvent): void;
    closeLogger(): void;
    openPhotoModal(opts: {
        target: 'pet' | 'user' | 'member';
        targetId?: string;
        currentAvatar?: string;
        title?: string;
    }): void;
    closePhotoModal(): void;
    updatePetAvatar(petId: string, avatarUrl: string): Promise<void>;
    updatePetProfile(petId: string, updates: Partial<Pet>): Promise<void>;
    updateUserAvatar(avatarUrl: string): Promise<void>;
    updateMemberAvatar(memberId: string, avatarUrl: string): Promise<void>;
    private loadPendingInvites;
    createInvite(roleName?: string): Promise<string>;
    revokeInvite(code: string): Promise<void>;
    exportEventsCsv(): void;
    exportFullBackupJson(): void;
    init(): Promise<void>;
    selectPet(pet: Pet): Promise<void>;
    selectHousehold(householdId: string): Promise<void>;
    refreshEvents(): Promise<void>;
    syncEvents(): Promise<void>;
    logEvent(eventType: EventType, notes?: string, metadata?: Record<string, any>, lat?: number, lng?: number, customTimestamp?: string): Promise<void>;
    updateEvent(eventId: string, eventType: EventType, notes?: string, metadata?: Record<string, any>, lat?: number, lng?: number, timestamp?: string): Promise<void>;
    deleteEvent(eventId: string): Promise<void>;
    handleNetworkChange(isOnline: boolean): Promise<void>;
    get isAuthenticated(): boolean;
    signOut(): void;
    signUp(dto: SignUpDTO): Promise<void>;
    signIn(dto: SignInDTO): Promise<void>;
    joinAuthenticated(code: string, role?: string): Promise<void>;
    claimHousehold(householdId: string, role?: string): Promise<void>;
    removeMember(memberId: string): Promise<void>;
    checkPendingSync(): Promise<void>;
}
export declare const appState: AppStateManager;
export {};
//# sourceMappingURL=appState.d.ts.map